name: fluttertodo
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  authentication_repository:
    path: packages/authentication_repository
  user_repository:
    path: packages/user_repository
  weather_repository:
    path: packages/weather_repository
  open_meteo_api:
    path: packages/open_meteo_api
  local_storage_todos_api:
    path: packages/local_storage_todos_api
  todos_api:
    path: packages/todos_api
  todos_repository:
    path: packages/todos_repository
  cupertino_icons: ^1.0.2
  intl: ^0.18.0
  bloc: ^8.1.0
  bloc_concurrency: ^0.2.0
  http: ^0.13.0
  flutter_bloc: ^8.1.1
  stream_transform: ^2.0.0
  equatable: ^2.0.3
  formz: ^0.6.0
  google_fonts: ^4.0.0
  hydrated_bloc: ^9.0.0
  json_annotation: ^4.4.0
  path_provider: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.1.0
  mocktail: ^0.3.0
  mockingjay: ^0.3.0
  build_runner: ^2.0.0
  json_serializable: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
